## Pandas 追加

この資料は[The Python Tutorial](https://docs.python.org/3.6/tutorial/index.html#the-python-tutorial)
    ([日本語版](https://docs.python.jp/3/tutorial/)) および [Python for Data Analysis:Wrangling with Pandas, Numpy and IPython](http://shop.oreilly.com/product/0636920050896.do)を参考に作成した。

## インデックスの階層化
Multiindex は pandas の重要な機能のひとつ。
Multiindex による階層化によって多次元データをより低次元の処理系での取り扱いを実現する。

### `pd.Series` の Multiindex
`pd.Series` クラスの Multiindex は:

In [10]:
import numpy as np
import pandas as pd
ser = pd.Series(np.random.randn(8), 
                 index=[["a", "a", "b", "c", "d", "d", "e", "e"],
                        ["2000","2010","2000","2000","2000","2010","2000","2010"]])
ser

a  2000    0.608605
   2010    0.117970
b  2000    0.165885
c  2000   -0.709062
d  2000   -0.562112
   2010   -0.277552
e  2000    0.171508
   2010   -1.111910
dtype: float64

これをインデックスで指定すると:

In [11]:
ser["a"]

2000    0.608605
2010    0.117970
dtype: float64

In [12]:
ser["b":"c"]

b  2000    0.165885
c  2000   -0.709062
dtype: float64

In [13]:
ser.loc[["a", "d"]]

a  2000    0.608605
   2010    0.117970
d  2000   -0.562112
   2010   -0.277552
dtype: float64

`iloc()` の働きは（もちろん）同じ:

In [14]:
ser.iloc[2:4]

b  2000    0.165885
c  2000   -0.709062
dtype: float64

低い階層のインデックスも指定するには、コンマで区切る:

In [15]:
ser["a","2000"]

0.6086054366042096

インデックスからデータセットを作り直すには、`pd.unstack()` が使える:

In [16]:
ser.unstack()

       2000      2010
a  0.608605  0.117970
b  0.165885       NaN
c -0.709062       NaN
d -0.562112 -0.277552
e  0.171508 -1.111910

`pd.stack()` は逆をおこなう:

In [17]:
ser.unstack().stack()

a  2000    0.608605
   2010    0.117970
b  2000    0.165885
c  2000   -0.709062
d  2000   -0.562112
   2010   -0.277552
e  2000    0.171508
   2010   -1.111910
dtype: float64

### `pd.DataFrame` の Multiindex
`pd.DataFrame` では行・列いずれにも Multiindex は適用できる:

In [18]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(24).reshape(6,4),
                 index =[["a", "a", "b", "b", "c", "c"],["2000", "2010", "2000", "2010", "2000", "2010"]],
                 columns = [["Tokyo", "Tokyo", "Saitama", "Nagano"],["Mainland", "Isrands", "Mainland", "Mainland"]])
df

           Tokyo             Saitama    Nagano
        Mainland   Isrands  Mainland  Mainland
a 2000  0.069428  2.546802  1.457338 -0.569397
  2010  0.460472  0.031973 -0.063079 -0.608645
b 2000  1.841005 -0.667141 -0.110929 -0.327752
  2010 -0.277205  0.300749 -2.123452  1.265280
c 2000 -0.454824  1.104094 -1.671802 -0.148097
  2010  0.583424 -1.297794 -0.512486 -0.485872

インデックスの指定は、`pd.Series`と同じ:

In [19]:
df["Tokyo"]

        Mainland   Isrands
a 2000  0.069428  2.546802
  2010  0.460472  0.031973
b 2000  1.841005 -0.667141
  2010 -0.277205  0.300749
c 2000 -0.454824  1.104094
  2010  0.583424 -1.297794

In [20]:
df["Tokyo","Mainland"]

a  2000    0.069428
   2010    0.460472
b  2000    1.841005
   2010   -0.277205
c  2000   -0.454824
   2010    0.583424
Name: (Tokyo, Mainland), dtype: float64

In [21]:
df.loc["a"]

         Tokyo             Saitama    Nagano
      Mainland   Isrands  Mainland  Mainland
2000  0.069428  2.546802  1.457338 -0.569397
2010  0.460472  0.031973 -0.063079 -0.608645

In [27]:
df["Tokyo","Mainland"]

a  2000    0.069428
   2010    0.460472
b  2000    1.841005
   2010   -0.277205
c  2000   -0.454824
   2010    0.583424
Name: (Tokyo, Mainland), dtype: float64

ただし、`pd.DataFrame` なのでスライスは行に対して適用される:

In [ ]:
df["a":"b"]

## Pandas のデータ読み込み

Pandas では CSV, XLS, JSON 形式といった様々な形式をシステムコールを使うよりも簡単にあつかうことができる。

### CSV 形式
CSV 形式の読み込みには、`pd.read_csv()`を使う。  
以下の例では、[Yahoo! Finance から取得したビットコイン-USD 交換レートデータ](https://finance.yahoo.com/quote/BTC-USD/history/)を読み込む。  
`pd.read_csv()` では Default で１行目、１列目がインデックスとして利用される:

In [35]:
import pandas as pd
df = pd.read_csv("BTC-USD.csv", index_col = 0, parse_dates=True)
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-07-16,0.049510,0.049510,0.049510,0.049510,0.049510,0
2010-07-17,0.049510,0.085850,0.059410,0.085840,0.085840,5
2010-07-18,0.085840,0.093070,0.077230,0.080800,0.080800,49
2010-07-19,0.080800,0.081810,0.074260,0.074740,0.074740,20
2010-07-20,0.074740,0.079210,0.066340,0.079210,0.079210,42
2010-07-21,0.079210,0.081810,0.050500,0.050500,0.050500,129
2010-07-22,0.050500,0.067670,0.050500,0.062620,0.062620,141
2010-07-23,0.062620,0.061610,0.050490,0.054540,0.054540,26
2010-07-24,0.054540,0.059410,0.050500,0.050500,0.050500,85
2010-07-25,0.050500,0.056000,0.050000,0.056000,0.056000,46
2010-07-26,0.056000,0.060500,0.053000,0.060000,0.060000,196
2010-07-27,0.060000,0.062000,0.054000,0.058900,0.058900,255
2010-07-28,0.058900,0.069900,0.057100,0.069900,0.069900,528
2010-07-29,0.069900,0.069800,0.058200,0.062700,0.062700,198
2010-07-30,0.062700,0.068890,0.056000,0.067850,0.067850,243
2010-07-31,0.067850,0.065000,0.060000,0.061100,0.061100,162
2010-08-01,0.061100,0.063300,0.060000,0.060000,0.060000,221
2010-08-02,0.060000,0.065000,0.059000,0.060000,0.060000,606
2010-08-03,0.060000,0.062310,0.057000,0.057000,0.057000,210
2010-08-04,0.057000,0.061000,0.058000,0.061000,0.061000,303
2010-08-05,0.061000,0.062400,0.060700,0.062300,0.062300,85
2010-08-06,0.062300,0.062200,0.059000,0.059000,0.059000,157
2010-08-07,0.059000,0.061000,0.059000,0.060900,0.060900,132
2010-08-08,0.060900,0.073500,0.059300,0.071000,0.071000,886
2010-08-09,0.071000,0.070900,0.066510,0.070000,0.070000,88
2010-08-10,0.070000,0.075410,0.060000,0.067000,0.067000,1015
2010-08-11,0.067000,0.070000,0.061410,0.070000,0.070000,134
2010-08-12,0.070000,0.068000,0.064500,0.064500,0.064500,233
2010-08-13,0.064500,0.069500,0.064500,0.067000,0.067000,295
2010-08-14,0.067000,0.067000,0.065000,0.065290,0.065290,294
...,...,...,...,...,...,...
2018-04-02,7074.649902,7528.970215,7039.879883,7434.299805,7434.299805,905326798
2018-04-03,7434.299805,7442.419922,6727.089844,6815.500000,6815.500000,877199782
2018-04-04,6815.500000,6933.660156,6602.379883,6790.450195,6790.450195,777145174
2018-04-05,6790.450195,6869.529785,6526.669922,6634.859863,6634.859863,605651287
2018-04-06,6634.859863,7083.850098,6624.470215,6917.200195,6917.200195,564883141
2018-04-07,6917.200195,7132.029785,6911.020020,7049.919922,7049.919922,425825572
2018-04-08,7049.919922,7204.279785,6633.689941,6789.529785,6789.529785,901883664
2018-04-09,6789.529785,6922.839844,6676.720215,6871.069824,6871.069824,424510977
2018-04-10,6871.069824,6999.370117,6839.160156,6977.129883,6977.129883,450141340
2018-04-11,6977.040039,8051.950195,6791.330078,7927.729980,7927.729980,1490759969
2018-04-12,7927.729980,8237.160156,7758.799805,7899.109863,7899.109863,1171435820
2018-04-13,7898.740234,8195.339844,7841.189941,8022.509766,8022.509766,537286381
2018-04-14,8022.509766,8437.030273,8021.040039,8376.730469,8376.730469,570527804
2018-04-15,8376.730469,8430.929688,7929.240234,8079.770020,8079.770020,713471956
2018-04-16,8079.770020,8187.600098,7858.120117,7921.629883,7921.629883,580880500
2018-04-17,7921.649902,8246.570313,7908.919922,8189.959961,8189.959961,593500791
2018-04-18,8189.919922,8321.009766,8136.419922,8301.820313,8301.820313,602099034
2018-04-19,8301.820313,8945.139648,8243.490234,8877.080078,8877.080078,979994921
2018-04-20,8877.150391,9047.820313,8631.179688,8935.719727,8935.719727,829073400
2018-04-21,8935.849609,9043.980469,8788.440430,8823.360352,8823.360352,610183093
2018-04-22,8823.459961,9025.730469,8804.200195,8968.250000,8968.250000,553892335
2018-04-23,8967.860352,9741.910156,8957.679688,9655.769531,9655.769531,1276464750
2018-04-24,9657.690430,9765.230469,8757.059570,8873.620117,8873.620117,1779806222
2018-04-25,8873.570313,9315.129883,8669.379883,9282.120117,9282.120117,997427934
2018-04-26,9289.009766,9385.870117,8923.480469,8938.469727,8938.469727,758182407
2018-04-27,8938.469727,9435.900391,8892.519531,9351.469727,9351.469727,774111704
2018-04-28,9349.940430,9552.669922,9189.070313,9407.040039,9407.040039,640931911
2018-04-29,9407.349609,9459.809570,9133.599609,9248.450195,9248.450195,574099218
2018-04-30,9248.250000,9251.660156,8851.099609,9077.280273,9077.280273,669555436
2018-05-01,9077.280273,9271.620117,8993.820313,9232.190430,9232.190430,527488395

### Microsoft Excel XLS 形式
Microsoft Exel の XLS 形式の読み込みには、`pd.read_xls()`を使う。  
以下の例は、総務省が公開している、[住民基本台帳に基づく人口動態データ](http://www.soumu.go.jp/menu_news/s-news/01gyosei02_02000148.html)を読み込んでいる:
- 列インデックスは、2-4 行目を Multiindex としてあつかっている
- 行インデックスは都道府県名で置き換えている

In [38]:
import pandas as pd
import numpy as np

df = pd.read_excel("000494956.xls", sheet_name=0, header=[1,2,3], skiprows=[4])
# Omit "Unnamed" indices and adjust 
for i, col in enumerate(df.columns.levels):
    columns = np.where(col.str.contains("Unnamed"), "", col)
    df.columns.set_levels(columns, level=i, inplace=True)
df.set_index("都道府県名", inplace=True)
df.index.name="都道府県名"
df

団体コード    平成29年                                平成28年                            \
            人口                         世帯数   住民票記載数
             男        女         計          転入者数（国内） 転入者数（国外）  転入者数（計）    出生者数
都道府県名
北海道    2537340  2833467   5370807  2761826   245573    13047   258620   35452
青森県     627006   696855   1323861   589887    34255     1880    36135    8684
岩手県     613838   663433   1277271   523065    36207     1870    38077    8363
宮城県    1131759  1187679   2319438   980808   106795     5049   111844   17569
秋田県     485257   543939   1029196   426020    21489     1270    22759    5692
山形県     538338   580130   1118468   411919    28062     1356    29418    7578
福島県     950430   988129   1938559   779244    54421     2781    57202   13810
茨城県    1482072  1478386   2960458  1221978    98859    15798   114657   21383
栃木県     993019   998578   1991597   817370    58970    10576    69546   14904
群馬県     988955  1009320   1998275   831970    60784     8721    69505   14201
埼玉県    3679223  3664584   7343807  3212080   321112    26278   347390   56108
千葉県    3137814  3145788   6283602  2811702   279946    33494   313440   46656
東京都    6675004  6855049  13530053  6994147   886814   117674  1004488  115742
神奈川県   4574910  4580479   9155389  4236072   441970    38089   480059   72794
新潟県    1116170  1184753   2300923   890293    57884     3967    61851   15853
富山県     520105   554600   1074705   414865    24318     3737    28055    7463
石川県     558006   595621   1153627   478395    34315     4021    38336    8985
福井県     385110   409323    794433   289825    18126     2712    20838    6171
山梨県     413919   430798    844717   356363    27740     2982    30722    5925
長野県    1036838  1089226   2126064   861074    63213     7930    71143   15393
岐阜県    1004919  1061347   2066266   809888    60365    11798    72163   15254
静岡県    1855174  1901691   3756865  1557733   128828    14885   143713   28423
愛知県    3775270  3756961   7532231  3214669   329622    45586   375208   66567
三重県     899701   942052   1841753   782840    55244     8045    63289   13797
滋賀県     699932   720328   1420260   566148    48032     5806    53838   12306
京都府    1232089  1337321   2569410  1202380   109701    11820   121521   19686
大阪府    4283835  4577602   8861437  4223735   387230    35800   423030   70281
兵庫県    2689585  2916960   5606545  2507945   196458    17726   214184   44135
奈良県     656316   723865   1380181   587413    41808     3475    45283    9539
和歌山県    466136   518553    984689   440150    22502     1500    24002    6704
鳥取県     274794   300470    575264   235502    15404     1135    16539    4473
島根県     333255   363127    696382   288790    18968     1989    20957    5337
岡山県     929475   998157   1927632   835989    65197     7542    72739   15627
広島県    1385401  1472074   2857475  1300322   110217    13268   123485   23074
山口県     668030   740558   1408588   659804    41468     3139    44607    9948
徳島県     364700   399513    764213   334117    21316     2032    23348    5381
香川県     482078   515733    997811   436123    30147     3551    33698    7606
愛媛県     666134   739191   1405325   651763    36137     3731    39868    9947
高知県     345444   387091    732535   352694    20632     1228    21860    4838
福岡県    2436091  2690298   5126389  2371459   256749    18896   275645   44603
佐賀県     397243   440734    837977   328015    25637     1722    27359    6871
長崎県     656314   736636   1392950   635020    44442     5167    49609   10974
熊本県     850608   947541   1798149   770607    75804     4141    79945   15026
大分県     558646   618245   1176891   533406    34224     3091    37315    9127
宮崎県     529293   590251   1119544   521627    34839     1604    36443    9009
鹿児島県    785168   882835   1668003   807169    60982     2150    63132   13756
沖縄県     723531   743540   1467071   632826    71989     5015    77004   16766

団体コード                    ...                                                \
                         ...     住民票消除数                         増減数(Ａ)-(Ｂ)
      その他（計）     計（Ａ）    ...    転出者数（計）    死亡者数 その他（計）     計（Ｂ）
都道府県名                    ...
北海道     2519   296591    ...     261537   62131   3326   326994     -30403
青森県      519    45338    ...      41994   17366    582    59942     -14604
岩手県      325    46765    ...      41338   16995    631    58964     -12199
宮城県     1158   130571    ...     110200   23579   1820   135599      -5028
秋田県      330    28781    ...      26717   15263    620    42600     -13819
山形県      240    37236    ...      32692   15222    414    48328     -11092
福島県      837    71849    ...      61875   24325    789    86989     -15140
茨城県     1325   137365    ...     111301   31551   4286   147138      -9773
栃木県      806    85256    ...      68582   21500   2441    92523      -7267
群馬県     1038    84744    ...      65958   22212   3619    91789      -7045
埼玉県     6306   409804    ...     311830   63696  13884   389410      20394
千葉県     4155   364251    ...     282066   56689   7793   346548      17703
東京都    16667  1136897    ...     875849  114580  31764  1022193     114704
神奈川県   16088   568941    ...     451660   78135  19908   549703      19238
新潟県      267    77971    ...      67022   28853    608    96483     -18512
富山県      294    35812    ...      27245   12943   1079    41267      -5455
石川県      412    47733    ...      37669   12490    989    51148      -3415
福井県      143    27152    ...      21800    9274    865    31939      -4787
山梨県      443    37090    ...      31606    9616    935    42157      -5067
長野県      917    87453    ...      71264   25231   2560    99055     -11602
岐阜県     1199    88616    ...      72242   22610   3693    98545      -9929
静岡県     1548   173684    ...     143949   39481   4008   187438     -13754
愛知県     5519   447294    ...     347120   65894  11685   424699      22595
三重県      992    78078    ...      63768   20212   2373    86353      -8275
滋賀県      717    66861    ...      52650   12625   1189    66464        397
京都府     1780   142987    ...     118855   26291   3273   148419      -5432
大阪府     5454   498765    ...     404176   86173  12481   502830      -4065
兵庫県     3236   261555    ...     215050   56257   4790   276097     -14542
奈良県      704    55526    ...      48223   14148    792    63163      -7637
和歌山県     438    31144    ...      27725   12683    364    40772      -9628
鳥取県      168    21180    ...      17488    7386    351    25225      -4045
島根県      257    26551    ...      21591    9595    377    31563      -5012
岡山県      392    88758    ...      71157   21675   2075    94907      -6149
広島県     1662   148221    ...     119955   30163   3839   153957      -5736
山口県      417    54972    ...      46666   18492   1007    66165     -11193
徳島県      313    29042    ...      24235    9863    788    34886      -5844
香川県      430    41734    ...      33172   11920   1004    46096      -4362
愛媛県      485    50300    ...      42518   17744    710    60972     -10672
高知県      284    26982    ...      23759   10363    384    34506      -7524
福岡県     3661   323909    ...     263223   51308   5437   319968       3941
佐賀県      370    34600    ...      28744    9754    582    39080      -4480
長崎県      496    61079    ...      52756   17214   2262    72232     -11153
熊本県     1033    96004    ...      85581   21419   1198   108198     -12194
大分県      565    47007    ...      39145   14313    619    54077      -7070
宮崎県      647    46099    ...      40141   13723    769    54633      -8534
鹿児島県     743    77631    ...      66699   21589    842    89130     -11499
沖縄県     1271    95041    ...      75959   11759   1483    89201       5840

団体コード
            増減率  自然増減数     自然増減率   社会増減数     社会増減率

都道府県名
北海道   -0.562892 -26679 -0.493945   -3724 -0.068948
青森県   -1.091101  -8682 -0.648653   -5922 -0.442447
岩手県   -0.946048  -8632 -0.669422   -3567 -0.276625
宮城県   -0.216308  -6010 -0.258554     982  0.042246
秋田県   -1.324909  -9571 -0.917628   -4248 -0.407281
山形県   -0.981975  -7644 -0.676724   -3448 -0.305252
福島県   -0.774940 -10515 -0.538210   -4625 -0.236730
茨城県   -0.329032 -10168 -0.342330     395  0.013299
栃木県   -0.363557  -6596 -0.329987    -671 -0.033569
群馬県   -0.351316  -8011 -0.399487     966  0.048172
埼玉県    0.278477  -7588 -0.103613   27982  0.382090
千葉県    0.282529 -10033 -0.160121   27736  0.442650
東京都    0.855021   1162  0.008662  113542  0.846359
神奈川県   0.210570  -5341 -0.058460   24579  0.269030
新潟県   -0.798125 -13000 -0.560481   -5512 -0.237644
富山県   -0.505018  -5480 -0.507332      25  0.002314
石川県   -0.295149  -3505 -0.302928      90  0.007778
福井県   -0.598959  -3103 -0.388254   -1684 -0.210705
山梨県   -0.596269  -3691 -0.434346   -1376 -0.161924
長野県   -0.542741  -9838 -0.460222   -1764 -0.082520
岐阜県   -0.478231  -7356 -0.354302   -2573 -0.123929
静岡県   -0.364768 -11058 -0.293267   -2696 -0.071500
愛知県    0.300880    673  0.008962   21922  0.291918
三重県   -0.447291  -6415 -0.346752   -1860 -0.100539
滋賀県    0.027960   -319 -0.022467     716  0.050427
京都府   -0.210964  -6605 -0.256521    1173  0.045556
大阪府   -0.045852 -15892 -0.179257   11827  0.133405
兵庫県   -0.258704 -12122 -0.215652   -2420 -0.043052
奈良県   -0.550288  -4609 -0.332104   -3028 -0.218184
和歌山県  -0.968303  -5979 -0.601317   -3649 -0.366986
鳥取県   -0.698246  -2913 -0.502840   -1132 -0.195405
島根県   -0.714577  -4258 -0.607077    -754 -0.107500
岡山県   -0.317978  -6048 -0.312755    -101 -0.005223
広島県   -0.200335  -7089 -0.247589    1353  0.047255
山口県   -0.788361  -8544 -0.601783   -2649 -0.186578
徳島県   -0.758905  -4482 -0.582035   -1362 -0.176870
香川県   -0.435254  -4314 -0.430465     -48 -0.004790
愛媛県   -0.753674  -7797 -0.550637   -2875 -0.203037
高知県   -1.016676  -5525 -0.746562   -1999 -0.270114
福岡県    0.076936  -6705 -0.130894   10646  0.207830
佐賀県   -0.531778  -2883 -0.342213   -1597 -0.189565
長崎県   -0.794315  -6240 -0.444412   -4913 -0.349903
熊本県   -0.673574  -6393 -0.353137   -5801 -0.320437
大分県   -0.597148  -5186 -0.438021   -1884 -0.159127
宮崎県   -0.756508  -4714 -0.417879   -3820 -0.338629
鹿児島県  -0.684667  -7833 -0.466388   -3666 -0.218279
沖縄県    0.399663   5007  0.342656     833  0.057007

[47 rows x 22 columns]